"""Health Timeline API endpoints — RFC-002 §3.2, §4.1.

Timeline is append-only and read-only via API. No update or delete endpoints.
"""

import uuid

from fastapi import APIRouter, Depends, Query
from sqlalchemy.ext.asyncio import AsyncSession

from health_one.platform.database import get_db
from health_one.platform.schemas.timeline import (
    TimelineEntryCreate,
    TimelineEntrySchema,
    TimelineResponse,
)
from health_one.platform.services.timeline import append_timeline_entry, get_timeline

router = APIRouter(prefix="/api/identities", tags=["Timeline"])


@router.get("/{identity_id}/timeline", response_model=TimelineResponse)
async def read_timeline(
    identity_id: uuid.UUID,
    event_type: str | None = Query(None, description="Filter by event type"),
    limit: int = Query(20, ge=1, le=100),
    offset: int = Query(0, ge=0),
    db: AsyncSession = Depends(get_db),
):
    """Read timeline entries for a Health Identity.

    Returns entries in reverse chronological order (newest first).
    Read-only — entries cannot be modified or deleted via API.
    """
    entries = await get_timeline(
        db,
        identity_id=identity_id,
        limit=limit,
        offset=offset,
        event_type=event_type,
    )
    # Ensure identity_id is always returned even if no timeline exists yet
    return TimelineResponse(
        timeline_id=uuid.uuid4(),  # generated on read if no timeline yet
        identity_id=identity_id,
        entries=[TimelineEntrySchema(**e) for e in entries],
    )


@router.post(
    "/{identity_id}/timeline/entries",
    response_model=TimelineEntrySchema,
    status_code=201,
)
async def append_entry(
    identity_id: uuid.UUID,
    body: TimelineEntryCreate,
    db: AsyncSession = Depends(get_db),
):
    """Append a Timeline entry for a Health Identity.

    This endpoint is primarily for internal/system use. Entries are append-only.
    In production, most entries are auto-generated by business events (service).
    """
    entry = await append_timeline_entry(
        db,
        identity_id=identity_id,
        event_type=body.event_type,
        source_object_type=body.source_object_type,
        source_object_id=body.source_object_id,
        summary_text=body.summary_text,
        performed_by=body.performed_by,
    )
    await db.commit()
    return TimelineEntrySchema(**entry)
